### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by zmughal** [NoScopeProductions/Void-Runner#32]
Add a link to the Play Store and a screenshot.

**Comment by StefanoFiumara** [comment]
Good call zaki :P

The description probably needs an update as well, I'll think up some words for that later.

**Comment by zmughal** [comment]
Hey, the image is .webp... I can't see it in Firefox <http://caniuse.com/#feat=webp>. Only works in Chrome/Chromium.

**Comment by StefanoFiumara** [comment]
Fixed the lazy way, with an imgur link.

**Comment by zmughal** [comment]
++ :fireworks: :-D
